@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMTZhNWE2Y2Q5ZDg1NDgwNjcyZWQ0YSIsImlhdCI6MTc3OTg2OTEwNCwiZXhwIjoxNzgwNDczOTA0fQ.a7O73lnjq6RUGhQW_DdsGsjd2linWkuoWqvqDtgy0xA
@analysisId = paste_analysis_id_here

###
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Jaykant Kumar",
  "email": "genius@example.com",
  "password": "your-password"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "genius@example.com",
  "password": "your-password"
}

###
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/crop/analyze
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=FarmLensBoundary

--FarmLensBoundary
Content-Disposition: form-data; name="text"

What disease is visible in this crop?
--FarmLensBoundary
Content-Disposition: form-data; name="media"; filename="crop.jpg"
Content-Type: image/jpeg

< ./uploads/sample.jpg
--FarmLensBoundary--

###
POST {{baseUrl}}/crop/chat
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "analysisId": "{{analysisId}}",
  "message": "Explain the treatment in simple Hindi."
}

###
GET {{baseUrl}}/crop/history
Authorization: Bearer {{token}}
