import { Download, Plus } from "lucide-react";

export default function HistoryHeader() {
  return (
    <section className="flex flex-col justify-between gap-6 rounded-3xl border bg-white p-8 shadow-sm md:flex-row md:items-center">

      <div>

        <h1 className="text-3xl font-bold">
          Analysis History
        </h1>

        <p className="mt-2 text-zinc-500">
          Review every crop analysis generated by FarmLens AI.
        </p>

      </div>

      <div className="flex gap-3">

        <button className="flex items-center gap-2 rounded-xl border px-5 py-3 hover:bg-zinc-100">
          <Download size={18} />
          Export
        </button>

        <button className="flex items-center gap-2 rounded-xl bg-green-600 px-5 py-3 text-white hover:bg-green-700">
          <Plus size={18} />
          Analyze Crop
        </button>

      </div>

    </section>
  );
}