import { BrainCircuit } from "lucide-react";

export default function AISummary() {
  return (
    <section className="rounded-3xl border bg-white p-6 shadow-sm">
      <div className="mb-5 flex items-center gap-3">
        <div className="rounded-xl bg-violet-100 p-3">
          <BrainCircuit className="text-violet-600" />
        </div>

        <div>
          <h2 className="text-xl font-bold">AI Summary</h2>
          <p className="text-sm text-zinc-500">
            Overall diagnosis generated by AI
          </p>
        </div>
      </div>

      <p className="leading-8 text-zinc-600">
        The uploaded tomato leaf shows clear symptoms of
        <span className="font-semibold text-green-600">
          {" "}Early Blight
        </span>.
        The infection appears to be in the moderate stage.
        Immediate fungicide treatment and removal of infected leaves are recommended.
      </p>
    </section>
  );
}